name: rit_grubpoint
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.4.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  google_sign_in: ^6.1.5
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.5
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.6
  dialog_flowtter: ^0.3.3
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO.png
    - assets/Aaharam.png
    - assets/little Rangoon.png
    - assets/the pacific cafe.png
    - assets/Cantina de Naples.png
    - assets/calcutta in a Box.png
    - assets/RITcanteenimage.png
    - assets/noodles.png
    - assets/pasta.png
    - assets/sodas.png
    - assets/dessert.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
