name: rit_grubpoint
description: A food delivery app for RIT students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.9.4
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.0
  qr_flutter: ^4.1.0
  # razorpay_flutter: ^1.3.5  # Commented out as it's not fully assembled yet
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  dialog_flowtter: ^0.3.3
  http: ^0.13.6
  google_nav_bar: ^5.0.6
  intl_phone_field: ^3.2.0
  pinput: ^4.0.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/LOGO.png
    - assets/Aaharam.png
    - assets/little Rangoon.png
    - assets/the pacific cafe.png
    - assets/Cantina de Naples.png
    - assets/calcutta in a Box.png
    - assets/RITcanteenimage.png
    - assets/noodles.png
    - assets/pasta.png
    - assets/sodas.png
    - assets/dessert.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
