name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Features
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  # Google Sign-In
  google_sign_in: ^6.3.0

  # UI + Icons
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

  # Image Picking
  image_picker: ^1.1.0

  # QR Code
  qr_flutter: ^4.1.0

  # Razorpay for Payments
  razorpay_flutter: ^1.3.5

  # State Management (optional, if using)
  provider: ^6.1.2

  # Toast messages
  fluttertoast: ^8.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
