name: rit_grubpoint
description: A food ordering app for RIT students
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  google_generative_ai: ^0.2.0
  cached_network_image: ^3.3.1
  responsive_framework: ^1.4.0
  http: ^1.1.0
  stripe_payment: ^1.1.4
  shimmer: ^3.0.0
  firebase_auth_web: ^5.9.0
  firebase_storage_web: ^3.7.0
  firebase_core_web: ^2.8.0
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/RITcanteenimage.png
    - assets/LOGO.png
    - assets/sodas.png
    - assets/pasta.png
    - assets/noodles.png
    - assets/dessert.png
    - assets/images/
    - assets/shops/aaharam.jpg
    - assets/shops/little_rangoon.jpg
    - assets/shops/pacific_cafe.jpg
    - assets/shops/cantina_de_naples.jpg
    - assets/shops/calcutta_in_a_box.jpg
